language: php

php:
  - 7.3

before_script:
  - cp .env.travis .env
  - mkdir -p storage/purify
  - composer self-update
  - composer install --no-interaction
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - php artisan key:generate
  - vendor/bin/phpunit

services:
  - redis-server

cache:
  directories:
    - vendor
